import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as solanaweb3 from "@solana/web3.js"
import { useWallet } from "@solana/wallet-adapter-react"
import { TOKEN_PROGRAM_ID } from '@solana/spl-token'
import { useState } from 'react'
import AccountInfo from '../Components/AccountInfo'
//here


export default function Home() {

  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      {/* sol */}
    <h1> Task 3</h1>
     <AccountInfo/>
    </main>

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
  </div>
  )
}
